### PR TITLE
Commit test for connecting detached head

### PR DESCRIPTION
**Pull request by ArashBigdeliNCO**
This is a test for pull request review.

### CODE REVIEW

**Review by StevenEarle-NCO — COMMENTED** [review]
Are all these files new? I can edit this ?

**Comment by ArashBigdeliNCO** [comment]
I can record a response here

**Comment by StevenEarle-NCO** [comment]
are these files new?

**Comment by ArashBigdeliNCO** [comment]
Should not be, probably because of detached head. 

and i can edit you :)

**Review by StevenEarle-NCO — APPROVED** [review]

**Pull request merged**
