### PR TITLE
Rfc 10000

### PR DESCRIPTION
**Pull request by ArashBigdeliNCO**
Random RFC name , hopefully rebase looks better now. 
It looks good to me except for one file.

### CODE REVIEW

**Comment by ArashBigdeliNCO** [comment]
I can also Merge without waiting for requirements to be met. I should change permission on members to get rid of this.

**Review by StevenEarle-NCO — COMMENTED** [review]
Woa!  we're keeping GFS online for 19 days???

**Review by StevenEarle-NCO — APPROVED** [review]

**Review by StevenEarle-NCO — APPROVED** [review]

**Comment by ArashBigdeliNCO** [comment]
Yep, we still do.

**Comment by ArashBigdeliNCO** [comment]
> Woa! we're keeping GFS online for 19 days???

yep we still do.

**Pull request merged**
